package com.ipodplayer3.app.ui.settings

object Strings {
    data class Bundle(
        val appName: String,
        val music: String,
        val songs: String,
        val albums: String,
        val artists: String,
        val coverFlow: String,
        val playlists: String,
        val search: String,
        val nowPlaying: String,
        val settings: String,
        val about: String,
        val shuffle: String,
        val repeat: String,
        val lyrics: String,
        val language: String,
        val theme: String,
        val clickSound: String,
        val vibrate: String,
        val equalizer: String,
        val bass: String,
        val treble: String,
        val on: String,
        val off: String,
        val all: String,
        val one: String,
        val none: String,
        val silver: String,
        val black: String,
        val u2: String,
        val zh: String,
        val en: String,
        val emptyLibrary: String,
        val permissionNeeded: String,
        val grant: String,
        val createPlaylist: String,
        val rename: String,
        val delete: String,
        val addSong: String,
        val removeSong: String,
        val playlistName: String,
        val confirm: String,
        val cancel: String,
        val searchHint: String,
        val noLyrics: String,
        val flat: String,
        val pop: String,
        val rock: String,
        val classical: String,
        val jazz: String,
        val bassBoost: String,
        val scanning: String,
        val trackCount: String,
    )

    fun of(lang: AppLanguage): Bundle = when (lang) {
        AppLanguage.ZH -> zh
        AppLanguage.EN -> en
    }

    private val zh = Bundle(
        appName = "iPod 播放器 3.0",
        music = "音乐",
        songs = "歌曲",
        albums = "专辑",
        artists = "艺术家",
        coverFlow = "Cover Flow",
        playlists = "播放列表",
        search = "搜索",
        nowPlaying = "正在播放",
        settings = "设置",
        about = "关于",
        shuffle = "随机播放",
        repeat = "重复",
        lyrics = "歌词",
        language = "语言",
        theme = "主题",
        clickSound = "按键音",
        vibrate = "震动",
        equalizer = "均衡器",
        bass = "低音",
        treble = "高音",
        on = "开",
        off = "关",
        all = "全部",
        one = "单曲",
        none = "关",
        silver = "银色",
        black = "黑色",
        u2 = "U2 黑红",
        zh = "简体中文",
        en = "English",
        emptyLibrary = "曲库为空，请在系统中添加音乐文件",
        permissionNeeded = "需要读取音频权限",
        grant = "授权",
        createPlaylist = "新建播放列表",
        rename = "重命名",
        delete = "删除",
        addSong = "添加歌曲",
        removeSong = "移出列表",
        playlistName = "列表名称",
        confirm = "确定",
        cancel = "取消",
        searchHint = "搜索歌曲、专辑、艺术家",
        noLyrics = "暂无歌词",
        flat = "原声",
        pop = "流行",
        rock = "摇滚",
        classical = "古典",
        jazz = "爵士",
        bassBoost = "低音增强",
        scanning = "正在扫描曲库…",
        trackCount = "首",
    )

    private val en = Bundle(
        appName = "iPod Player 3.0",
        music = "Music",
        songs = "Songs",
        albums = "Albums",
        artists = "Artists",
        coverFlow = "Cover Flow",
        playlists = "Playlists",
        search = "Search",
        nowPlaying = "Now Playing",
        settings = "Settings",
        about = "About",
        shuffle = "Shuffle",
        repeat = "Repeat",
        lyrics = "Lyrics",
        language = "Language",
        theme = "Theme",
        clickSound = "Click Sound",
        vibrate = "Vibration",
        equalizer = "Equalizer",
        bass = "Bass",
        treble = "Treble",
        on = "On",
        off = "Off",
        all = "All",
        one = "One",
        none = "Off",
        silver = "Silver",
        black = "Black",
        u2 = "U2 Black Red",
        zh = "简体中文",
        en = "English",
        emptyLibrary = "Library is empty. Add music files on your device.",
        permissionNeeded = "Audio permission required",
        grant = "Grant",
        createPlaylist = "New Playlist",
        rename = "Rename",
        delete = "Delete",
        addSong = "Add Song",
        removeSong = "Remove",
        playlistName = "Playlist Name",
        confirm = "OK",
        cancel = "Cancel",
        searchHint = "Search songs, albums, artists",
        noLyrics = "No lyrics",
        flat = "Flat",
        pop = "Pop",
        rock = "Rock",
        classical = "Classical",
        jazz = "Jazz",
        bassBoost = "Bass Boost",
        scanning = "Scanning library…",
        trackCount = "tracks",
    )
}
